---
kind: pipeline
name: preview

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:18-alpine
    commands:
      - yarn install --frozen-lockfile

  - name: ignore-openapi
    image: node:18-alpine
    commands:
      - apk add git
      - ./scripts/ignore-openapi

  - name: build
    image: node:18-alpine
    env:
          NODE_OPTIONS: "--max_old_space_size=7168"
    commands:
      - yarn build

  - name: package
    image: registry.suse.com/bci/bci-base:15.4
    commands:
      - zypper install -y zip
      - zip -q -r build.zip build/

  - name: preview
    image: ghcr.io/harvester/drone-netlify:master
    environment:
      BUILD_ZIP_FILE: "build.zip"
      NETLIFY_AUTH_TOKEN:
        from_secret: NETLIFY_AUTH_TOKEN
      NETLIFY_SITE_ID:
        from_secret: NETLIFY_SITE_ID
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN

trigger:
  event:
    - pull_request

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:18-alpine
    commands:
      - yarn install --frozen-lockfile

  - name: build
    image: node:18-alpine
    env:
          NODE_OPTIONS: "--max_old_space_size=7168"
    commands:
      - yarn build

  - name: release
    image: registry.suse.com/bci/nodejs:18
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm install -g gh-pages
      - ./scripts/gh-pages

trigger:
  branch:
    - main
  event:
    - push