/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
  api: [
    {
      type: "category",
      label: "API",
      link: {
        type: "generated-index",
        title: "Harvester API",
        description:
          "This is the API doc of the Harvester server. The APIs are broken down into the categories below:",
      },
      items: require("./docs/api/sidebar.js"),
    },
  ],
};
module.exports = sidebars;