#!/bin/sh
set -e

AUTHOR_USER=${DRONE_COMMIT_AUTHOR}
AUTHOR_EMAIL=${DRONE_COMMIT_AUTHOR_EMAIL}

GITHUB_REPO_LINK="${DRONE_REPO_LINK}.git"
GITHUB_REPO_WITH_TOKEN=$(echo ${GITHUB_REPO_LINK} | sed "s/\/\//\/\/${GITHUB_TOKEN}@/g")

gh-pages -d build \
        -o origin \
        -m "deploy: ${DRONE_COMMIT}" \
        -u "${AUTHOR_USER} <${AUTHOR_EMAIL}>" \
        -r ${GITHUB_REPO_WITH_TOKEN} \
        -b gh-pages-test