#!/bin/sh

# ignore if the api folder not exists or api/swagger.json not exists.
if [ ! -d "api" ] || [ ! -f "api/swagger.json" ]; then
    exit 0
fi

BEFORE_COMMIT_ID=${DRONE_COMMIT_BEFORE}
AFTER_COMMIT_ID=${DRONE_COMMIT}

FILES=$(git --no-pager diff --name-only ${BEFORE_COMMIT_ID}...${AFTER_COMMIT_ID})

# if the api/swaggers.json has changed
if echo "$FILES" | grep -q "api/swagger.json"; then
    # perform re-generate and check for dirty files
    yarn clean-api-docs all
    yarn gen-api-docs all
    dirty_files=$(git status --porcelain --untracked-files=no)
    # exit 0 if dirty_file is empty
    if [ -z "$dirty_files" ]; then
        exit 0
    fi

    lines_count=$(echo "$dirty_files" | wc -l)
    if [ "$lines_count" -gt 1 ] || { [ "$lines_count" -eq 1 ] && [[ "$dirty_files" != *"harvester-apis.info.mdx"* ]]; }; then
        echo "Error: Found dirty files. Please resolve the issues before continuing."
        exit 1
    fi

    git reset --hard HEAD
    exit 0
fi

# if the files in the docs/api have changed
if echo "$FILES" | grep -q "docs/api/"; then
    exit 0
fi

# ignore if the docs/api folder not exists.
if [ ! -d "docs/api" ]; then
    exit 0
fi

# if no any change then don't build the openapi documents.
rm -rf docs/api/*.mdx
cat << EOF > docs/api/sidebar.js
module.exports = [];
EOF