#!/bin/sh

API_DIRECTORY="api"

# ignore if the api folder not exists or api/swagger.json not exists.
if [ ! -d $API_DIRECTORY ] || [ -z "$(ls $API_DIRECTORY)" ]; then
    exit 0
fi

BEFORE_COMMIT_ID=${DRONE_COMMIT_BEFORE}
AFTER_COMMIT_ID=${DRONE_COMMIT}

FILES=$(git --no-pager diff --name-only ${BEFORE_COMMIT_ID}...${AFTER_COMMIT_ID})

# if the api/swaggers.json has changed
if echo "$FILES" | grep -qE "v(.*)swagger.json"; then
    # perform re-generate and check for dirty files
    yarn clean-api-docs && yarn gen-api-docs
    dirty_files=$(git status --porcelain --untracked-files=no | grep -v "harvester-apis.info.mdx")
    # exit 0 if dirty_file is empty
    if [ -z "$dirty_files" ]; then
        echo "Not any dirty files found."
        git reset --hard HEAD
        exit 0
    fi

    lines_count=$(echo "$dirty_files" | wc -l)
    if [ "$lines_count" -gt 1 ] || [ "$lines_count" -eq 1 ]; then
        echo "Error: Found dirty files. Please resolve the issues before continuing."
        exit 1
    fi

    git reset --hard HEAD
    exit 0
fi

# if the files in the docs/api have changed
if echo "$FILES" | grep -q "$API_DIRECTORY/*.mdx"; then
    exit 0
fi

# ignore if the docs/api folder not exists.
if [ -d "docs/$API_DIRECTORY" ]; then
    # if no any change then don't build the openapi documents.
    rm -rf docs/$API_DIRECTORY/*.mdx
    cat << EOF > docs/$API_DIRECTORY/sidebar.js
module.exports = [];
EOF
    echo "Cleaned openapi documents in docs/$API_DIRECTORY"
fi

# if versioned_docs/*/api folder exist
matching_folders=(versioned_docs/*/api)
if [ ${#matching_folders[@]} -gt 0 ]; then
    for folder in "${matching_folders[@]}"; do
        rm -rf $folder/*.mdx
        cat << EOF > $folder/sidebar.js
module.exports = [];
EOF
    echo "Cleaned openapi documents in $folder"
    done
fi